# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.18

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /workspaces/oop_labs-4

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /workspaces/oop_labs-4

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /workspaces/oop_labs-4/CMakeFiles /workspaces/oop_labs-4//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /workspaces/oop_labs-4/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named tests

# Build rule for target.
tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tests
.PHONY : tests

# fast build rule for target.
tests/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/build
.PHONY : tests/fast

#=============================================================================
# Target rules for targets named lab7_exe

# Build rule for target.
lab7_exe: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lab7_exe
.PHONY : lab7_exe

# fast build rule for target.
lab7_exe/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lab7_exe.dir/build.make CMakeFiles/lab7_exe.dir/build
.PHONY : lab7_exe/fast

#=============================================================================
# Target rules for targets named lab7_lib

# Build rule for target.
lab7_lib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lab7_lib
.PHONY : lab7_lib

# fast build rule for target.
lab7_lib/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lab7_lib.dir/build.make CMakeFiles/lab7_lib.dir/build
.PHONY : lab7_lib/fast

#=============================================================================
# Target rules for targets named gmock_main

# Build rule for target.
gmock_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock_main
.PHONY : gmock_main

# fast build rule for target.
gmock_main/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googlemock/CMakeFiles/gmock_main.dir/build.make _deps/googletest-build/googlemock/CMakeFiles/gmock_main.dir/build
.PHONY : gmock_main/fast

#=============================================================================
# Target rules for targets named gmock

# Build rule for target.
gmock: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock
.PHONY : gmock

# fast build rule for target.
gmock/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googlemock/CMakeFiles/gmock.dir/build.make _deps/googletest-build/googlemock/CMakeFiles/gmock.dir/build
.PHONY : gmock/fast

#=============================================================================
# Target rules for targets named gtest_main

# Build rule for target.
gtest_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest_main
.PHONY : gtest_main

# fast build rule for target.
gtest_main/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googletest/CMakeFiles/gtest_main.dir/build.make _deps/googletest-build/googletest/CMakeFiles/gtest_main.dir/build
.PHONY : gtest_main/fast

#=============================================================================
# Target rules for targets named gtest

# Build rule for target.
gtest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest
.PHONY : gtest

# fast build rule for target.
gtest/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googletest/CMakeFiles/gtest.dir/build.make _deps/googletest-build/googletest/CMakeFiles/gtest.dir/build
.PHONY : gtest/fast

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lab7_exe.dir/build.make CMakeFiles/lab7_exe.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lab7_exe.dir/build.make CMakeFiles/lab7_exe.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lab7_exe.dir/build.make CMakeFiles/lab7_exe.dir/main.cpp.s
.PHONY : main.cpp.s

src/coroutine.o: src/coroutine.cpp.o

.PHONY : src/coroutine.o

# target to build an object file
src/coroutine.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lab7_lib.dir/build.make CMakeFiles/lab7_lib.dir/src/coroutine.cpp.o
.PHONY : src/coroutine.cpp.o

src/coroutine.i: src/coroutine.cpp.i

.PHONY : src/coroutine.i

# target to preprocess a source file
src/coroutine.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lab7_lib.dir/build.make CMakeFiles/lab7_lib.dir/src/coroutine.cpp.i
.PHONY : src/coroutine.cpp.i

src/coroutine.s: src/coroutine.cpp.s

.PHONY : src/coroutine.s

# target to generate assembly for a file
src/coroutine.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lab7_lib.dir/build.make CMakeFiles/lab7_lib.dir/src/coroutine.cpp.s
.PHONY : src/coroutine.cpp.s

src/druid.o: src/druid.cpp.o

.PHONY : src/druid.o

# target to build an object file
src/druid.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lab7_lib.dir/build.make CMakeFiles/lab7_lib.dir/src/druid.cpp.o
.PHONY : src/druid.cpp.o

src/druid.i: src/druid.cpp.i

.PHONY : src/druid.i

# target to preprocess a source file
src/druid.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lab7_lib.dir/build.make CMakeFiles/lab7_lib.dir/src/druid.cpp.i
.PHONY : src/druid.cpp.i

src/druid.s: src/druid.cpp.s

.PHONY : src/druid.s

# target to generate assembly for a file
src/druid.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lab7_lib.dir/build.make CMakeFiles/lab7_lib.dir/src/druid.cpp.s
.PHONY : src/druid.cpp.s

src/elf.o: src/elf.cpp.o

.PHONY : src/elf.o

# target to build an object file
src/elf.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lab7_lib.dir/build.make CMakeFiles/lab7_lib.dir/src/elf.cpp.o
.PHONY : src/elf.cpp.o

src/elf.i: src/elf.cpp.i

.PHONY : src/elf.i

# target to preprocess a source file
src/elf.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lab7_lib.dir/build.make CMakeFiles/lab7_lib.dir/src/elf.cpp.i
.PHONY : src/elf.cpp.i

src/elf.s: src/elf.cpp.s

.PHONY : src/elf.s

# target to generate assembly for a file
src/elf.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lab7_lib.dir/build.make CMakeFiles/lab7_lib.dir/src/elf.cpp.s
.PHONY : src/elf.cpp.s

src/factory.o: src/factory.cpp.o

.PHONY : src/factory.o

# target to build an object file
src/factory.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lab7_lib.dir/build.make CMakeFiles/lab7_lib.dir/src/factory.cpp.o
.PHONY : src/factory.cpp.o

src/factory.i: src/factory.cpp.i

.PHONY : src/factory.i

# target to preprocess a source file
src/factory.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lab7_lib.dir/build.make CMakeFiles/lab7_lib.dir/src/factory.cpp.i
.PHONY : src/factory.cpp.i

src/factory.s: src/factory.cpp.s

.PHONY : src/factory.s

# target to generate assembly for a file
src/factory.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lab7_lib.dir/build.make CMakeFiles/lab7_lib.dir/src/factory.cpp.s
.PHONY : src/factory.cpp.s

src/knight.o: src/knight.cpp.o

.PHONY : src/knight.o

# target to build an object file
src/knight.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lab7_lib.dir/build.make CMakeFiles/lab7_lib.dir/src/knight.cpp.o
.PHONY : src/knight.cpp.o

src/knight.i: src/knight.cpp.i

.PHONY : src/knight.i

# target to preprocess a source file
src/knight.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lab7_lib.dir/build.make CMakeFiles/lab7_lib.dir/src/knight.cpp.i
.PHONY : src/knight.cpp.i

src/knight.s: src/knight.cpp.s

.PHONY : src/knight.s

# target to generate assembly for a file
src/knight.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lab7_lib.dir/build.make CMakeFiles/lab7_lib.dir/src/knight.cpp.s
.PHONY : src/knight.cpp.s

src/logger.o: src/logger.cpp.o

.PHONY : src/logger.o

# target to build an object file
src/logger.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lab7_lib.dir/build.make CMakeFiles/lab7_lib.dir/src/logger.cpp.o
.PHONY : src/logger.cpp.o

src/logger.i: src/logger.cpp.i

.PHONY : src/logger.i

# target to preprocess a source file
src/logger.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lab7_lib.dir/build.make CMakeFiles/lab7_lib.dir/src/logger.cpp.i
.PHONY : src/logger.cpp.i

src/logger.s: src/logger.cpp.s

.PHONY : src/logger.s

# target to generate assembly for a file
src/logger.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lab7_lib.dir/build.make CMakeFiles/lab7_lib.dir/src/logger.cpp.s
.PHONY : src/logger.cpp.s

src/npc.o: src/npc.cpp.o

.PHONY : src/npc.o

# target to build an object file
src/npc.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lab7_lib.dir/build.make CMakeFiles/lab7_lib.dir/src/npc.cpp.o
.PHONY : src/npc.cpp.o

src/npc.i: src/npc.cpp.i

.PHONY : src/npc.i

# target to preprocess a source file
src/npc.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lab7_lib.dir/build.make CMakeFiles/lab7_lib.dir/src/npc.cpp.i
.PHONY : src/npc.cpp.i

src/npc.s: src/npc.cpp.s

.PHONY : src/npc.s

# target to generate assembly for a file
src/npc.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lab7_lib.dir/build.make CMakeFiles/lab7_lib.dir/src/npc.cpp.s
.PHONY : src/npc.cpp.s

src/observer.o: src/observer.cpp.o

.PHONY : src/observer.o

# target to build an object file
src/observer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lab7_lib.dir/build.make CMakeFiles/lab7_lib.dir/src/observer.cpp.o
.PHONY : src/observer.cpp.o

src/observer.i: src/observer.cpp.i

.PHONY : src/observer.i

# target to preprocess a source file
src/observer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lab7_lib.dir/build.make CMakeFiles/lab7_lib.dir/src/observer.cpp.i
.PHONY : src/observer.cpp.i

src/observer.s: src/observer.cpp.s

.PHONY : src/observer.s

# target to generate assembly for a file
src/observer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lab7_lib.dir/build.make CMakeFiles/lab7_lib.dir/src/observer.cpp.s
.PHONY : src/observer.cpp.s

src/visitor.o: src/visitor.cpp.o

.PHONY : src/visitor.o

# target to build an object file
src/visitor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lab7_lib.dir/build.make CMakeFiles/lab7_lib.dir/src/visitor.cpp.o
.PHONY : src/visitor.cpp.o

src/visitor.i: src/visitor.cpp.i

.PHONY : src/visitor.i

# target to preprocess a source file
src/visitor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lab7_lib.dir/build.make CMakeFiles/lab7_lib.dir/src/visitor.cpp.i
.PHONY : src/visitor.cpp.i

src/visitor.s: src/visitor.cpp.s

.PHONY : src/visitor.s

# target to generate assembly for a file
src/visitor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lab7_lib.dir/build.make CMakeFiles/lab7_lib.dir/src/visitor.cpp.s
.PHONY : src/visitor.cpp.s

tests_07/lab7_gtests.o: tests_07/lab7_gtests.cpp.o

.PHONY : tests_07/lab7_gtests.o

# target to build an object file
tests_07/lab7_gtests.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests_07/lab7_gtests.cpp.o
.PHONY : tests_07/lab7_gtests.cpp.o

tests_07/lab7_gtests.i: tests_07/lab7_gtests.cpp.i

.PHONY : tests_07/lab7_gtests.i

# target to preprocess a source file
tests_07/lab7_gtests.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests_07/lab7_gtests.cpp.i
.PHONY : tests_07/lab7_gtests.cpp.i

tests_07/lab7_gtests.s: tests_07/lab7_gtests.cpp.s

.PHONY : tests_07/lab7_gtests.s

# target to generate assembly for a file
tests_07/lab7_gtests.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests_07/lab7_gtests.cpp.s
.PHONY : tests_07/lab7_gtests.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... gmock"
	@echo "... gmock_main"
	@echo "... gtest"
	@echo "... gtest_main"
	@echo "... lab7_exe"
	@echo "... lab7_lib"
	@echo "... tests"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... src/coroutine.o"
	@echo "... src/coroutine.i"
	@echo "... src/coroutine.s"
	@echo "... src/druid.o"
	@echo "... src/druid.i"
	@echo "... src/druid.s"
	@echo "... src/elf.o"
	@echo "... src/elf.i"
	@echo "... src/elf.s"
	@echo "... src/factory.o"
	@echo "... src/factory.i"
	@echo "... src/factory.s"
	@echo "... src/knight.o"
	@echo "... src/knight.i"
	@echo "... src/knight.s"
	@echo "... src/logger.o"
	@echo "... src/logger.i"
	@echo "... src/logger.s"
	@echo "... src/npc.o"
	@echo "... src/npc.i"
	@echo "... src/npc.s"
	@echo "... src/observer.o"
	@echo "... src/observer.i"
	@echo "... src/observer.s"
	@echo "... src/visitor.o"
	@echo "... src/visitor.i"
	@echo "... src/visitor.s"
	@echo "... tests_07/lab7_gtests.o"
	@echo "... tests_07/lab7_gtests.i"
	@echo "... tests_07/lab7_gtests.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

